sudo: false
language: python
cache: pip
dist: bionic

matrix:
  include:
    - python: 3.9
      env: TOXENV=docs
    - python: 3.5
      env: TOXENV=prospector
    - python: 3.5
      env: TOXENV=py35-2.2
    - python: 3.6
      env: TOXENV=py36-2.2
    - python: 3.7
      env: TOXENV=py37-2.2
    - python: 3.8
      env: TOXENV=py38-2.2
    - python: pypy3
      env: TOXENV=pypy3-2.2
    - python: 3.6
      env: TOXENV=py36-3.0
    - python: 3.7
      env: TOXENV=py37-3.0
    - python: 3.8
      env: TOXENV=py38-3.0
    - python: pypy3
      env: TOXENV=pypy3-3.0
    - python: 3.6
      env: TOXENV=py36-3.1
    - python: 3.7
      env: TOXENV=py37-3.1
    - python: 3.8
      env: TOXENV=py38-3.1
    - python: pypy3
      env: TOXENV=pypy3-3.1
    - python: 3.6
      env: TOXENV=py36-3.2
    - python: 3.7
      env: TOXENV=py37-3.2
    - python: 3.8
      env: TOXENV=py38-3.2
    - python: 3.9
      env: TOXENV=py39-3.2
    - python: pypy3
      env: TOXENV=pypy3-3.2
    - python: 3.8
      env: TOXENV=py38-main
    - python: 3.9
      env: TOXENV=py39-main
# TODO: Enable when Python 3.10 is released.
#    - python: 3.10
#      env: TOXENV=py310-main
    - python: pypy3
      env: TOXENV=pypy3-main
  allow_failures:
    - python: 3.8
      env: TOXENV=py38-main
    - python: 3.9
      env: TOXENV=py39-main
# TODO: Enable when Python 3.10 is released.
#    - python: 3.10
#      env: TOXENV=py10-main
    - python: pypy3
      env: TOXENV=pypy3-main
install:
    - pip wheel -r tests/requirements.txt codecov
    - pip install virtualenv codecov tox
script:
  - tox
after_success: codecov
