sudo: false
language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.5
      env: TOXENV=prospector
    - python: 3.5
      env: TOXENV=py35-2.2
    - python: 3.6
      env: TOXENV=py36-2.2
    - python: 3.7
      env: TOXENV=py37-2.2
    - python: pypy3
      env: TOXENV=pypy3-2.2
    - python: 3.6
      env: TOXENV=py36-3.0
    - python: 3.7
      env: TOXENV=py37-3.0
    - python: 3.8
      env: TOXENV=py38-3.0
    - python: pypy3
      env: TOXENV=pypy3-3.0
    - python: 3.6
      env: TOXENV=py36-master
    - python: 3.7
      env: TOXENV=py37-master
    - python: 3.8
      env: TOXENV=py38-master
    - python: pypy3
      env: TOXENV=pypy3-master
  allow_failures:
    - python: 3.6
      env: TOXENV=py36-master
    - python: 3.7
      env: TOXENV=py37-master
    - python: 3.8
      env: TOXENV=py38-master
    - python: pypy3
      env: TOXENV=pypy3-master
install:
    - pip wheel -r tests/requirements.txt codecov
    - pip install virtualenv codecov tox
script:
  - tox
after_success: codecov
