sudo: no
language: python
cache: pip

matrix:
  include:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.5
      env: TOXENV=prospector
    - python: 3.6
      env: TOXENV=isort
    - python: 2.7
      env: TOXENV=py27-1.8
    - python: 2.7
      env: TOXENV=py27-1.9
    - python: 2.7
      env: TOXENV=py27-1.10
    - python: 2.7
      env: TOXENV=py27-1.11
    - python: 3.3
      env: TOXENV=py33-1.8
    - python: 3.4
      env: TOXENV=py34-1.8
    - python: 3.4
      env: TOXENV=py34-1.9
    - python: 3.4
      env: TOXENV=py34-1.10
    - python: 3.4
      env: TOXENV=py34-1.11
    - python: 3.5
      env: TOXENV=py35-1.9
    - python: 3.5
      env: TOXENV=py35-1.10
    - python: 3.5
      env: TOXENV=py35-1.11
    - python: 3.5
      env: TOXENV=py35-master
    - python: 3.6
      env: TOXENV=py36-1.11
    - python: 3.6
      env: TOXENV=py36-master
  allow_failures:
    - python: 3.5
      env: TOXENV=py35-master
    - python: 3.6
      env: TOXENV=py36-master
install:
    - pip wheel -r tests/requirements.txt codecov
    - pip install virtualenv codecov tox
script:
  - tox
after_success: codecov
